# Generated by Django 5.1.1 on 2025-09-09 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=255, null=True)),
                ('field2', models.CharField(blank=True, max_length=255, null=True)),
                ('field3', models.CharField(blank=True, max_length=255, null=True)),
                ('field4', models.CharField(blank=True, max_length=255, null=True)),
                ('field5', models.CharField(blank=True, max_length=255, null=True)),
                ('field6', models.CharField(blank=True, max_length=255, null=True)),
                ('field7', models.CharField(blank=True, max_length=255, null=True)),
                ('field8', models.CharField(blank=True, max_length=255, null=True)),
                ('field9', models.CharField(blank=True, max_length=255, null=True)),
                ('field10', models.CharField(blank=True, max_length=255, null=True)),
                ('field11', models.CharField(blank=True, max_length=255, null=True)),
                ('current_stage', models.CharField(choices=[('FILLING', 'Filling Stage'), ('APPROVAL', 'Approval Stage'), ('COMPLETED', 'Completed')], default='FILLING', max_length=20)),
                ('current_filler_step', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow.workflowdocument')),
            ],
            options={
                'unique_together': {('document', 'approver')},
            },
        ),
    ]
